default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: "postgresql://postgres:postgres@localhost:5432/samwest_development"

test:
  <<: *default
  url: "postgresql://postgres:postgres@localhost:5432/samwest_test"

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
